package android.app.faunadex.utils

import android.util.Log
import com.google.firebase.firestore.FirebaseFirestore
import kotlinx.coroutines.tasks.await

/**
 * Utility to seed initial animal data into Firebase Firestore
 *
 * USAGE: Call FirebaseDataSeeder.seedAnimals(firestore) once from your app
 * After data is seeded, you can comment out or remove the call
 */
object FirebaseDataSeeder {

    /**
     * Parse population string to integer
     * Examples: "~1,000 (1970s estimate)" -> 1000, "<400" -> 400, "~2,400" -> 2400
     */
    private fun parsePopulation(populationStr: String): Int {
        return try {
            // Remove all non-digit characters except for the first number group
            val cleanedStr = populationStr
                .replace("~", "")
                .replace("<", "")
                .replace(">", "")
                .replace(",", "")
                .replace(".", "")
                .split("(")[0] // Take only the part before any parentheses
                .trim()

            cleanedStr.toIntOrNull() ?: 0
        } catch (e: Exception) {
            Log.e("FirebaseDataSeeder", "Error parsing population: $populationStr", e)
            0
        }
    }

    suspend fun seedAnimals(firestore: FirebaseFirestore) {
        val animalsCollection = firestore.collection("animals")

        val sampleAnimals = listOf(
            // 1. Sumatran Tiger
            mapOf(
                "name_en" to "Sumatran Tiger",
                "name_id" to "Harimau Sumatera",
                "category_en" to "Mammal",
                "category_id" to "Mamalia",
                "description_en" to "The smallest surviving tiger subspecies, known for its heavy black stripes.",
                "description_id" to "Subspesies harimau terkecil yang masih hidup, dikenal dengan garis-garis hitamnya yang rapat.",
                "long_description_en" to "The Sumatran tiger is the only surviving tiger population in the Sunda Islands. They are distinguished by darker fur and broader stripes than other tigers. They are apex predators crucial for maintaining the health of the rainforest ecosystem.",
                "long_description_id" to "Harimau Sumatera adalah satu-satunya populasi harimau yang masih hidup di Kepulauan Sunda. Mereka dibedakan oleh bulu yang lebih gelap dan garis-garis yang lebih lebar dibandingkan harimau lainnya. Mereka adalah predator puncak yang sangat penting untuk menjaga kesehatan ekosistem hutan hujan.",
                "fun_fact_en" to "They have webbed toes that make them excellent swimmers.",
                "fun_fact_id" to "Mereka memiliki selaput di sela-sela jari kaki yang membuat mereka menjadi perenang yang handal.",
                "audio_url_en" to null,
                "audio_url_id" to null,
                "activity_period_en" to "Nocturnal / Crepuscular",
                "activity_period_id" to "Nokturnal / Krepuskular",
                "diet_en" to "Carnivore",
                "diet_id" to "Karnivora",
                "habitat_en" to "Lowland forest, mountain forest, peat swamp forest",
                "habitat_id" to "Hutan dataran rendah, hutan pegunungan, hutan rawa gambut",
                "lifespan_en" to "15-20 years",
                "lifespan_id" to "15-20 tahun",
                "city_en" to "N/A (Found in Gunung Leuser, Kerinci Seblat, Bukit Barisan Selatan)",
                "city_id" to "Tidak ada (Ditemukan di Gunung Leuser, Kerinci Seblat, Bukit Barisan Selatan)",
                "country_en" to "Indonesia",
                "country_id" to "Indonesia",
                "endemic_status_en" to "Endemic to Sumatra",
                "endemic_status_id" to "Endemik di Sumatera",
                "population_trend_en" to "Decreasing",
                "population_trend_id" to "Menurun",
                "protection_type_en" to "Protected by Law No. 5 of 1990",
                "protection_type_id" to "Dilindungi UU No. 5 Tahun 1990",
                "rarity_level_en" to "Critically Endangered",
                "rarity_level_id" to "Kritis",
                "size_category_en" to "Large",
                "size_category_id" to "Besar",
                "special_title_en" to "King of the Jungle",
                "special_title_id" to "Raja Hutan",
                "scientific_name" to "Panthera tigris sumatrae",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "domain" to "Eukaryota",
                "class" to "Mammalia",
                "order" to "Carnivora",
                "family" to "Felidae",
                "genus" to "Panthera",
                "species" to "P. tigris",
                "conservation_status" to "CR",
                "ar_model_url" to null,
                "image_url" to null,
                "is_protected" to true,
                "latitude" to -1.6000,
                "longitude" to 101.5000,
                "length" to "220-255 cm",
                "weight" to "75-140 kg",
                "population_past" to 1000,
                "population_present" to 400
            ) to "sumatran_tiger",

            // 2. Sumatran Rhinoceros
            mapOf(
                "name_en" to "Sumatran Rhinoceros",
                "name_id" to "Badak Sumatera",
                "category_en" to "Mammal",
                "category_id" to "Mamalia",
                "description_en" to "The smallest living rhinoceros and the only Asian rhino with two horns.",
                "description_id" to "Badak terkecil yang masih hidup dan satu-satunya badak Asia yang memiliki dua cula.",
                "long_description_en" to "Also known as the hairy rhinoceros, this shy and solitary animal is the most threatened rhinoceros species. It is covered in reddish-brown hair and is the closest living relative to the extinct Woolly Rhinoceros.",
                "long_description_id" to "Dikenal juga sebagai badak berbulu, hewan pemalu dan penyendiri ini adalah spesies badak yang paling terancam punah. Tubuhnya ditutupi rambut cokelat kemerahan dan merupakan kerabat terdekat yang masih hidup dari Badak Berbulu (Woolly Rhinoceros) yang telah punah.",
                "fun_fact_en" to "They are known as the \"singing rhino\" because they vocalize with whistles and squeaks.",
                "fun_fact_id" to "Mereka dikenal sebagai \"badak bernyanyi\" karena berkomunikasi dengan siulan dan lengkingan.",
                "audio_url_en" to null,
                "audio_url_id" to null,
                "activity_period_en" to "Crepuscular / Nocturnal",
                "activity_period_id" to "Krepuskular / Nokturnal",
                "diet_en" to "Herbivore (Browser)",
                "diet_id" to "Herbivora (Pemakan semak)",
                "habitat_en" to "Tropical rainforests, cloud forests",
                "habitat_id" to "Hutan hujan tropis, hutan kabut",
                "lifespan_en" to "35-40 years",
                "lifespan_id" to "35-40 tahun",
                "city_en" to "N/A (Found in Way Kambas, Gunung Leuser)",
                "city_id" to "Tidak ada (Ditemukan di Way Kambas, Gunung Leuser)",
                "country_en" to "Indonesia",
                "country_id" to "Indonesia",
                "endemic_status_en" to "Endemic to Sumatra and Borneo (Extinct in Malaysia)",
                "endemic_status_id" to "Endemik di Sumatera dan Kalimantan (Punah di Malaysia)",
                "population_trend_en" to "Decreasing",
                "population_trend_id" to "Menurun",
                "protection_type_en" to "Protected by Law No. 5 of 1990",
                "protection_type_id" to "Dilindungi UU No. 5 Tahun 1990",
                "rarity_level_en" to "Critically Endangered",
                "rarity_level_id" to "Kritis",
                "size_category_en" to "Large",
                "size_category_id" to "Besar",
                "special_title_en" to "Hairy Rhino",
                "special_title_id" to "Badak Berbulu",
                "scientific_name" to "Dicerorhinus sumatrensis",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "domain" to "Eukaryota",
                "class" to "Mammalia",
                "order" to "Perissodactyla",
                "family" to "Rhinocerotidae",
                "genus" to "Dicerorhinus",
                "species" to "D. sumatrensis",
                "conservation_status" to "CR",
                "ar_model_url" to null,
                "image_url" to null,
                "is_protected" to true,
                "latitude" to -4.9200,
                "longitude" to 105.7500,
                "length" to "236-318 cm",
                "weight" to "500-1000 kg",
                "population_past" to 600,
                "population_present" to 80
            ) to "sumatran_rhinoceros",

            // 3. Sumatran Elephant
            mapOf(
                "name_en" to "Sumatran Elephant",
                "name_id" to "Gajah Sumatera",
                "category_en" to "Mammal",
                "category_id" to "Mamalia",
                "description_en" to "A subspecies of the Asian elephant, smaller and with lighter skin pigmentation.",
                "description_id" to "Subspesies gajah Asia, berukuran lebih kecil dan memiliki pigmentasi kulit yang lebih terang.",
                "long_description_en" to "Sumatran elephants are the largest land mammals in Indonesia. They are highly social animals that live in herds led by a matriarch. They play a vital role in dispersing seeds in the forest.",
                "long_description_id" to "Gajah Sumatera adalah mamalia darat terbesar di Indonesia. Mereka adalah hewan sosial yang hidup dalam kawanan yang dipimpin oleh betina tertua (matriark). Mereka memainkan peran vital dalam penyebaran biji di hutan.",
                "fun_fact_en" to "They can consume up to 150 kg of food per day.",
                "fun_fact_id" to "Mereka dapat mengonsumsi hingga 150 kg makanan per hari.",
                "audio_url_en" to null,
                "audio_url_id" to null,
                "activity_period_en" to "Diurnal / Nocturnal",
                "activity_period_id" to "Diurnal / Nokturnal",
                "diet_en" to "Herbivore",
                "diet_id" to "Herbivora",
                "habitat_en" to "Lowland forest",
                "habitat_id" to "Hutan dataran rendah",
                "lifespan_en" to "60-70 years",
                "lifespan_id" to "60-70 tahun",
                "city_en" to "N/A (Found in Riau, Lampung, Aceh)",
                "city_id" to "Tidak ada (Ditemukan di Riau, Lampung, Aceh)",
                "country_en" to "Indonesia",
                "country_id" to "Indonesia",
                "endemic_status_en" to "Endemic to Sumatra",
                "endemic_status_id" to "Endemik di Sumatera",
                "population_trend_en" to "Decreasing",
                "population_trend_id" to "Menurun",
                "protection_type_en" to "Protected by Law No. 5 of 1990",
                "protection_type_id" to "Dilindungi UU No. 5 Tahun 1990",
                "rarity_level_en" to "Critically Endangered",
                "rarity_level_id" to "Kritis",
                "size_category_en" to "Very Large",
                "size_category_id" to "Sangat Besar",
                "special_title_en" to "Giant of Sumatra",
                "special_title_id" to "Raksasa Sumatera",
                "scientific_name" to "Elephas maximus sumatranus",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "domain" to "Eukaryota",
                "class" to "Mammalia",
                "order" to "Proboscidea",
                "family" to "Elephantidae",
                "genus" to "Elephas",
                "species" to "E. maximus",
                "conservation_status" to "CR",
                "ar_model_url" to null,
                "image_url" to null,
                "is_protected" to true,
                "latitude" to 0.9000,
                "longitude" to 101.5000,
                "length" to "550-640 cm",
                "weight" to "2000-4000 kg",
                "population_past" to 2800,
                "population_present" to 2400
            ) to "sumatran_elephant",

            // 4. Tapanuli Orangutan
            mapOf(
                "name_en" to "Tapanuli Orangutan",
                "name_id" to "Orangutan Tapanuli",
                "category_en" to "Mammal",
                "category_id" to "Mamalia",
                "description_en" to "The rarest species of great ape, described as a distinct species in 2017.",
                "description_id" to "Spesies kera besar paling langka, dideskripsikan sebagai spesies terpisah pada tahun 2017.",
                "long_description_en" to "Found only in the Batang Toru Ecosystem, this orangutan species is genetically distinct from both Sumatran and Bornean orangutans. They have frizzier hair and a flatter face.",
                "long_description_id" to "Hanya ditemukan di Ekosistem Batang Toru, spesies orangutan ini berbeda secara genetik dari orangutan Sumatera dan Kalimantan. Mereka memiliki rambut yang lebih keriting dan wajah yang lebih datar.",
                "fun_fact_en" to "Their \"long call\" has a higher pitch than other orangutans.",
                "fun_fact_id" to "\"Panggilan panjang\" (long call) mereka memiliki nada yang lebih tinggi dibandingkan orangutan lain.",
                "audio_url_en" to null,
                "audio_url_id" to null,
                "activity_period_en" to "Diurnal",
                "activity_period_id" to "Diurnal",
                "diet_en" to "Omnivore (Frugivore dominant)",
                "diet_id" to "Omnivora (Dominan buah-buahan)",
                "habitat_en" to "Upland tropical rainforest",
                "habitat_id" to "Hutan hujan tropis dataran tinggi",
                "lifespan_en" to "50-60 years",
                "lifespan_id" to "50-60 tahun",
                "city_en" to "South Tapanuli",
                "city_id" to "Tapanuli Selatan",
                "country_en" to "Indonesia",
                "country_id" to "Indonesia",
                "endemic_status_en" to "Endemic to Batang Toru",
                "endemic_status_id" to "Endemik di Batang Toru",
                "population_trend_en" to "Decreasing",
                "population_trend_id" to "Menurun",
                "protection_type_en" to "Protected by Law No. 5 of 1990",
                "protection_type_id" to "Dilindungi UU No. 5 Tahun 1990",
                "rarity_level_en" to "Critically Endangered",
                "rarity_level_id" to "Kritis",
                "size_category_en" to "Medium",
                "size_category_id" to "Sedang",
                "special_title_en" to "Rarest Great Ape",
                "special_title_id" to "Kera Besar Paling Langka",
                "scientific_name" to "Pongo tapanuliensis",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "domain" to "Eukaryota",
                "class" to "Mammalia",
                "order" to "Primates",
                "family" to "Hominidae",
                "genus" to "Pongo",
                "species" to "P. tapanuliensis",
                "conservation_status" to "CR",
                "ar_model_url" to null,
                "image_url" to null,
                "is_protected" to true,
                "latitude" to 1.8300,
                "longitude" to 99.0800,
                "length" to "110-137 cm",
                "weight" to "40-90 kg",
                "population_past" to 1500,
                "population_present" to 800
            ) to "tapanuli_orangutan",

            // 5. Sumatran Orangutan
            mapOf(
                "name_en" to "Sumatran Orangutan",
                "name_id" to "Orangutan Sumatera",
                "category_en" to "Mammal",
                "category_id" to "Mamalia",
                "description_en" to "A critically endangered great ape arboreal species found in northern Sumatra.",
                "description_id" to "Spesies kera besar arboreal yang sangat terancam punah dan ditemukan di Sumatera bagian utara.",
                "long_description_en" to "Sumatran orangutans are almost exclusively arboreal, spending most of their time in trees to avoid predators like tigers. They are more social than their Bornean cousins and are known for using tools.",
                "long_description_id" to "Orangutan Sumatera hampir sepenuhnya arboreal, menghabiskan sebagian besar waktunya di pohon untuk menghindari predator seperti harimau. Mereka lebih sosial dibandingkan kerabatnya di Kalimantan dan dikenal pandai menggunakan alat.",
                "fun_fact_en" to "They have the longest birth interval of any land mammal (approx 9 years).",
                "fun_fact_id" to "Mereka memiliki jarak kelahiran terlama dibandingkan mamalia darat manapun (sekitar 9 tahun).",
                "audio_url_en" to null,
                "audio_url_id" to null,
                "activity_period_en" to "Diurnal",
                "activity_period_id" to "Diurnal",
                "diet_en" to "Omnivore (Frugivore dominant)",
                "diet_id" to "Omnivora (Dominan buah-buahan)",
                "habitat_en" to "Tropical rainforest, peat swamp",
                "habitat_id" to "Hutan hujan tropis, rawa gambut",
                "lifespan_en" to "45-50 years",
                "lifespan_id" to "45-50 tahun",
                "city_en" to "N/A (Found in Aceh, North Sumatra)",
                "city_id" to "Tidak ada (Ditemukan di Aceh, Sumatera Utara)",
                "country_en" to "Indonesia",
                "country_id" to "Indonesia",
                "endemic_status_en" to "Endemic to Sumatra",
                "endemic_status_id" to "Endemik di Sumatera",
                "population_trend_en" to "Decreasing",
                "population_trend_id" to "Menurun",
                "protection_type_en" to "Protected by Law No. 5 of 1990",
                "protection_type_id" to "Dilindungi UU No. 5 Tahun 1990",
                "rarity_level_en" to "Critically Endangered",
                "rarity_level_id" to "Kritis",
                "size_category_en" to "Medium",
                "size_category_id" to "Sedang",
                "special_title_en" to "Man of the Forest",
                "special_title_id" to "Orang Hutan",
                "scientific_name" to "Pongo abelii",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "domain" to "Eukaryota",
                "class" to "Mammalia",
                "order" to "Primates",
                "family" to "Hominidae",
                "genus" to "Pongo",
                "species" to "P. abelii",
                "conservation_status" to "CR",
                "ar_model_url" to null,
                "image_url" to null,
                "is_protected" to true,
                "latitude" to 3.5000,
                "longitude" to 97.5000,
                "length" to "125-150 cm",
                "weight" to "45-90 kg",
                "population_past" to 85000,
                "population_present" to 14600
            ) to "sumatran_orangutan",

            // 6. Sumatran Serow
            mapOf(
                "name_en" to "Sumatran Serow",
                "name_id" to "Kambing Hutan Sumatera",
                "category_en" to "Mammal",
                "category_id" to "Mamalia",
                "description_en" to "A goat-antelope species found in the mountains of Sumatra.",
                "description_id" to "Spesies kambing-antelop yang ditemukan di pegunungan Sumatera.",
                "long_description_en" to "The Sumatran Serow is a solitary and territorial animal often found on steep limestone cliffs and mountain slopes. They have short horns and a dark coat with a mane running down their neck.",
                "long_description_id" to "Kambing Hutan Sumatera adalah hewan penyendiri dan teritorial yang sering ditemukan di tebing kapur curam dan lereng pegunungan. Mereka memiliki tanduk pendek dan bulu gelap dengan surai di lehernya.",
                "fun_fact_en" to "They are excellent climbers and can scale steep cliffs to escape predators.",
                "fun_fact_id" to "Mereka adalah pemanjat yang ulung dan dapat memanjat tebing curam untuk melarikan diri dari predator.",
                "audio_url_en" to null,
                "audio_url_id" to null,
                "activity_period_en" to "Diurnal / Crepuscular",
                "activity_period_id" to "Diurnal / Krepuskular",
                "diet_en" to "Herbivore",
                "diet_id" to "Herbivora",
                "habitat_en" to "Montane forest, limestone hills",
                "habitat_id" to "Hutan pegunungan, bukit kapur",
                "lifespan_en" to "10-20 years",
                "lifespan_id" to "10-20 tahun",
                "city_en" to "N/A (Found in Barisan Mountains)",
                "city_id" to "Tidak ada (Ditemukan di Pegunungan Bukit Barisan)",
                "country_en" to "Indonesia",
                "country_id" to "Indonesia",
                "endemic_status_en" to "Endemic to Sumatra",
                "endemic_status_id" to "Endemik di Sumatera",
                "population_trend_en" to "Decreasing",
                "population_trend_id" to "Menurun",
                "protection_type_en" to "Protected by Law No. 5 of 1990",
                "protection_type_id" to "Dilindungi UU No. 5 Tahun 1990",
                "rarity_level_en" to "Vulnerable",
                "rarity_level_id" to "Rentan",
                "size_category_en" to "Medium",
                "size_category_id" to "Sedang",
                "special_title_en" to "Mountain Ghost",
                "special_title_id" to "Hantu Gunung",
                "scientific_name" to "Capricornis sumatraensis",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "domain" to "Eukaryota",
                "class" to "Mammalia",
                "order" to "Artiodactyla",
                "family" to "Bovidae",
                "genus" to "Capricornis",
                "species" to "C. sumatraensis",
                "conservation_status" to "VU",
                "ar_model_url" to null,
                "image_url" to null,
                "is_protected" to true,
                "latitude" to -2.0000,
                "longitude" to 101.0000,
                "length" to "140-180 cm",
                "weight" to "85-140 kg",
                "population_past" to 0,
                "population_present" to 0
            ) to "sumatran_serow",

            // 7. Sumatran Ground Cuckoo
            mapOf(
                "name_en" to "Sumatran Ground Cuckoo",
                "name_id" to "Tokhtor Sumatera",
                "category_en" to "Bird",
                "category_id" to "Burung",
                "description_en" to "A large, elusive terrestrial cuckoo species endemic to Sumatra.",
                "description_id" to "Spesies burung kukuk darat besar yang sulit dipahami dan endemik di Sumatera.",
                "long_description_en" to "This bird dwells on the forest floor in the Barisan Mountains. It was considered extinct for nearly a century before being rediscovered in 1997. It has striking green, blue, and purple plumage around the eyes.",
                "long_description_id" to "Burung ini tinggal di lantai hutan di Pegunungan Bukit Barisan. Sempat dianggap punah selama hampir satu abad sebelum ditemukan kembali pada tahun 1997. Memiliki bulu berwarna hijau, biru, dan ungu yang mencolok di sekitar mata.",
                "fun_fact_en" to "It was \"lost\" to science for 81 years (1916-1997).",
                "fun_fact_id" to "Burung ini \"hilang\" dari sains selama 81 tahun (1916-1997).",
                "audio_url_en" to null,
                "audio_url_id" to null,
                "activity_period_en" to "Diurnal",
                "activity_period_id" to "Diurnal",
                "diet_en" to "Carnivore (Insects, small vertebrates)",
                "diet_id" to "Karnivora (Serangga, vertebrata kecil)",
                "habitat_en" to "Montane rainforest floor",
                "habitat_id" to "Lantai hutan hujan pegunungan",
                "lifespan_en" to "Unknown (Estimated 10-15 years)",
                "lifespan_id" to "Tidak diketahui (Estimasi 10-15 tahun)",
                "city_en" to "N/A (Found in Bukit Barisan Selatan)",
                "city_id" to "Tidak ada (Ditemukan di Bukit Barisan Selatan)",
                "country_en" to "Indonesia",
                "country_id" to "Indonesia",
                "endemic_status_en" to "Endemic to Sumatra",
                "endemic_status_id" to "Endemik di Sumatera",
                "population_trend_en" to "Decreasing",
                "population_trend_id" to "Menurun",
                "protection_type_en" to "Protected by Law No. 5 of 1990",
                "protection_type_id" to "Dilindungi UU No. 5 Tahun 1990",
                "rarity_level_en" to "Critically Endangered",
                "rarity_level_id" to "Kritis",
                "size_category_en" to "Small (for an animal, large for a cuckoo)",
                "size_category_id" to "Kecil",
                "special_title_en" to "The Rediscovered Jewel",
                "special_title_id" to "Permata yang Ditemukan Kembali",
                "scientific_name" to "Carpococcyx viridis",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "domain" to "Eukaryota",
                "class" to "Aves",
                "order" to "Cuculiformes",
                "family" to "Cuculidae",
                "genus" to "Carpococcyx",
                "species" to "C. viridis",
                "conservation_status" to "CR",
                "ar_model_url" to null,
                "image_url" to null,
                "is_protected" to true,
                "latitude" to -5.0000,
                "longitude" to 104.0000,
                "length" to "55 cm",
                "weight" to "Data Unavailable",
                "population_past" to 0,
                "population_present" to 150
            ) to "sumatran_ground_cuckoo",

            // 8. Mentawai Macaque
            mapOf(
                "name_en" to "Mentawai Macaque (Pagai Island Macaque)",
                "name_id" to "Beruk Mentawai (Bokoi)",
                "category_en" to "Mammal",
                "category_id" to "Mamalia",
                "description_en" to "A primate species found only on the Mentawai Islands, known locally as \"Bokoi\".",
                "description_id" to "Spesies primata yang hanya ditemukan di Kepulauan Mentawai, dikenal secara lokal sebagai \"Bokoi\".",
                "long_description_en" to "The Mentawai macaque is darker than other macaques, with dark brown fur on the back and pale neck sides. They live in social groups and are adapted to life in the unique ecosystem of the Mentawai islands.",
                "long_description_id" to "Beruk Mentawai berwarna lebih gelap dari makaka lainnya, dengan bulu coklat tua di punggung dan sisi leher yang pucat. Mereka hidup dalam kelompok sosial dan beradaptasi dengan kehidupan di ekosistem unik kepulauan Mentawai.",
                "fun_fact_en" to "They have specialized cheek pouches to store food while foraging.",
                "fun_fact_id" to "Mereka memiliki kantung pipi khusus untuk menyimpan makanan saat mencari makan.",
                "audio_url_en" to null,
                "audio_url_id" to null,
                "activity_period_en" to "Diurnal",
                "activity_period_id" to "Diurnal",
                "diet_en" to "Omnivore (Frugivore dominant)",
                "diet_id" to "Omnivora (Dominan buah-buahan)",
                "habitat_en" to "Primary and secondary rainforest, swamp forest",
                "habitat_id" to "Hutan hujan primer dan sekunder, hutan rawa",
                "lifespan_en" to "20-25 years",
                "lifespan_id" to "20-25 tahun",
                "city_en" to "N/A (Mentawai Islands)",
                "city_id" to "Tidak ada (Kepulauan Mentawai)",
                "country_en" to "Indonesia",
                "country_id" to "Indonesia",
                "endemic_status_en" to "Endemic to Mentawai Islands",
                "endemic_status_id" to "Endemik di Kepulauan Mentawai",
                "population_trend_en" to "Decreasing",
                "population_trend_id" to "Menurun",
                "protection_type_en" to "Protected by Law No. 5 of 1990",
                "protection_type_id" to "Dilindungi UU No. 5 Tahun 1990",
                "rarity_level_en" to "Critically Endangered",
                "rarity_level_id" to "Kritis",
                "size_category_en" to "Small / Medium",
                "size_category_id" to "Kecil / Sedang",
                "special_title_en" to "Bokoi",
                "special_title_id" to "Bokoi",
                "scientific_name" to "Macaca pagensis",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "domain" to "Eukaryota",
                "class" to "Mammalia",
                "order" to "Primates",
                "family" to "Cercopithecidae",
                "genus" to "Macaca",
                "species" to "M. pagensis",
                "conservation_status" to "CR",
                "ar_model_url" to null,
                "image_url" to null,
                "is_protected" to true,
                "latitude" to -2.5000,
                "longitude" to 100.0000,
                "length" to "45-55 cm",
                "weight" to "6-14.5 kg",
                "population_past" to 15000,
                "population_present" to 2900
            ) to "mentawai_macaque"
        )

        try {
            var successCount = 0
            sampleAnimals.forEach { (animalData, docId) ->
                animalsCollection.document(docId).set(animalData).await()
                Log.d("FirebaseDataSeeder", "✓ Added: ${animalData["name_en"]}")
                successCount++
            }
            Log.d("FirebaseDataSeeder", "🎉 Successfully added $successCount animals to Firebase!")
        } catch (e: Exception) {
            Log.e("FirebaseDataSeeder", "❌ Error adding animals: ${e.message}", e)
            throw e
        }
    }
}