package android.app.faunadex.utils

import android.util.Log
import com.google.firebase.firestore.FirebaseFirestore
import kotlinx.coroutines.tasks.await

/**
 * Utility to seed initial animal data into Firebase Firestore
 *
 * USAGE: Call FirebaseDataSeeder.seedAnimals(firestore) once from your app
 * After data is seeded, you can comment out or remove the call
 */
object FirebaseDataSeeder {

    suspend fun seedAnimals(firestore: FirebaseFirestore) {
        val animalsCollection = firestore.collection("animals")

        val sampleAnimals = listOf(
            // 1. Amur Leopard
            hashMapOf(
                "name_en" to "Amur Leopard",
                "name_id" to "Macan Tutul Amur",
                "scientific_name" to "Panthera pardus orientalis",
                "category_en" to "mammal",
                "category_id" to "mamalia",
                "conservation_status" to "CR",
                "habitat_en" to "Temperate broadleaf and mixed forests",
                "habitat_id" to "Hutan berdaun lebar dan hutan campuran iklim sedang",
                "description_en" to "The Amur leopard is the rarest big cat in the world. It is adapted to the cold climate of the Russian Far East and China with thick fur.",
                "description_id" to "Macan tutul Amur adalah kucing besar paling langka di dunia. Hewan ini beradaptasi dengan iklim dingin Timur Jauh Rusia dan Tiongkok dengan bulu yang tebal.",
                "long_description_en" to "The Amur leopard is a leopard subspecies native to the Primorye region of southeastern Russia and northern China. It is listed as Critically Endangered on the IUCN Red List. In 2007, only 19–26 wild leopards were estimated to survive, but recent conservation efforts have increased numbers to over 100. It differs from other subspecies by its thick, pale cream-colored fur, widely spaced rosettes, and long legs for walking through snow.",
                "long_description_id" to "Macan tutul Amur adalah subspesies macan tutul yang berasal dari wilayah Primorye di tenggara Rusia dan Tiongkok utara. Hewan ini terdaftar sebagai Kritis (Critically Endangered) dalam Daftar Merah IUCN. Pada tahun 2007, diperkirakan hanya 19–26 ekor yang bertahan hidup di alam liar, namun upaya konservasi baru-baru ini telah meningkatkan jumlahnya menjadi lebih dari 100 ekor. Ia berbeda dari subspesies lain karena bulunya yang tebal berwarna krem pucat, pola bunga (roset) yang berjarak lebar, dan kaki panjang untuk berjalan menembus salju.",
                "fun_fact_en" to "Amur leopards have distinct rosette patterns that are widely spaced and have thick borders, like a fingerprint!",
                "fun_fact_id" to "Macan tutul Amur memiliki pola bunga yang unik dengan jarak lebar dan garis tebal, mirip seperti sidik jari manusia!",
                "diet_en" to "Carnivore - Deer, wild boars, hares",
                "diet_id" to "Karnivora - Rusa, babi hutan, kelinci",
                "lifespan_en" to "10-15 years",
                "lifespan_id" to "10-15 tahun",
                "weight" to "32-48 kg",
                "length" to "107-136 cm",
                "special_title_en" to "Rarest Big Cat",
                "special_title_id" to "Kucing Besar Paling Langka",
                "endemic_status_en" to "Endemic to Russian Far East & China",
                "endemic_status_id" to "Endemik Timur Jauh Rusia & Tiongkok",
                "population_trend_en" to "Increasing",
                "population_trend_id" to "Meningkat",
                "activity_period_en" to "Crepuscular",
                "activity_period_id" to "Krepuskular (Senja/Fajar)",
                "is_protected" to true,
                "protection_type_en" to "Protected by Law",
                "protection_type_id" to "Dilindungi Undang-Undang",
                "size_category_en" to "Large",
                "size_category_id" to "Besar",
                "rarity_level_en" to "Critically Rare",
                "rarity_level_id" to "Sangat Langka",
                "population_past" to 2000,
                "population_present" to 120,
                "latitude" to 43.1155,
                "longitude" to 131.8855,
                "country_en" to "Russia",
                "country_id" to "Rusia",
                "city_en" to "Primorsky Krai",
                "city_id" to "Primorsky Krai",
                "domain" to "Eukarya",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "class" to "Mammalia",
                "order" to "Carnivora",
                "family" to "Felidae",
                "genus" to "Panthera",
                "species" to "P. pardus orientalis",
                "image_url" to null,
                "ar_model_url" to null,
                "audio_url_en" to null,
                "audio_url_id" to null
            ) to "amur_leopard",

            // 2. Angel Shark
            hashMapOf(
                "name_en" to "Angel Shark",
                "name_id" to "Hiu Malaikat",
                "scientific_name" to "Squatina squatina",
                "category_en" to "fish",
                "category_id" to "ikan",
                "conservation_status" to "CR",
                "habitat_en" to "Coastal sandy or muddy seabeds",
                "habitat_id" to "Dasar laut berpasir atau berlumpur di pesisir",
                "description_en" to "A flat-bodied shark that resembles a ray. It buries itself in the sand to ambush prey.",
                "description_id" to "Hiu bertubuh pipih yang menyerupai ikan pari. Ia mengubur dirinya di dalam pasir untuk menyergap mangsa.",
                "long_description_en" to "The Angel Shark is a species of shark in the family Squatinidae. Once widespread in the northeastern Atlantic Ocean, its numbers have declined dramatically due to intensive commercial fishing. It is perfectly adapted for camouflage on the sea floor, with a flattened body and broad pectoral fins. It lies in wait, buried in sediment with only its eyes showing, ready to strike at passing fish.",
                "long_description_id" to "Hiu Malaikat adalah spesies hiu dalam famili Squatinidae. Pernah tersebar luas di Samudra Atlantik timur laut, jumlahnya telah menurun drastis akibat penangkapan ikan komersial yang intensif. Hiu ini beradaptasi sempurna untuk kamuflase di dasar laut, dengan tubuh pipih dan sirip dada yang lebar. Ia berbaring menunggu, terkubur dalam sedimen dengan hanya mata yang terlihat, siap menyerang ikan yang lewat.",
                "fun_fact_en" to "They can ambush prey in one-tenth of a second!",
                "fun_fact_id" to "Mereka bisa menyergap mangsa hanya dalam sepersepuluh detik!",
                "diet_en" to "Carnivore - Flatfishes, skates, crustaceans",
                "diet_id" to "Karnivora - Ikan pipih, pari, krustasea",
                "lifespan_en" to "10-15 years",
                "lifespan_id" to "10-15 tahun",
                "weight" to "80 kg",
                "length" to "1.5-2.4 m",
                "special_title_en" to "Ambush Hunter of the Sands",
                "special_title_id" to "Pemburu Penyergap Pasir",
                "endemic_status_en" to "Native to NE Atlantic & Mediterranean",
                "endemic_status_id" to "Asli Atlantik Timur Laut & Mediterania",
                "population_trend_en" to "Decreasing",
                "population_trend_id" to "Menurun",
                "activity_period_en" to "Nocturnal",
                "activity_period_id" to "Nokturnal",
                "is_protected" to true,
                "protection_type_en" to "Protected by Law (Select Regions)",
                "protection_type_id" to "Dilindungi Undang-Undang (Wilayah Tertentu)",
                "size_category_en" to "Large",
                "size_category_id" to "Besar",
                "rarity_level_en" to "Critically Rare",
                "rarity_level_id" to "Sangat Langka",
                "population_past" to 100000,
                "population_present" to 5000,
                "latitude" to 28.2916,
                "longitude" to -16.6291,
                "country_en" to "Spain (Canary Islands)",
                "country_id" to "Spanyol (Kepulauan Canary)",
                "city_en" to "Canary Islands",
                "city_id" to "Kepulauan Canary",
                "domain" to "Eukarya",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "class" to "Chondrichthyes",
                "order" to "Squatiniformes",
                "family" to "Squatinidae",
                "genus" to "Squatina",
                "species" to "S. squatina",
                "image_url" to null,
                "ar_model_url" to null,
                "audio_url_en" to null,
                "audio_url_id" to null
            ) to "angel_shark",

            // 3. Axolotl
            hashMapOf(
                "name_en" to "Axolotl",
                "name_id" to "Axolotl",
                "scientific_name" to "Ambystoma mexicanum",
                "category_en" to "amphibian",
                "category_id" to "amfibi",
                "conservation_status" to "CR",
                "habitat_en" to "Freshwater lakes and canals",
                "habitat_id" to "Danau air tawar dan kanal",
                "description_en" to "A unique salamander that retains its larval features throughout its life, known for its ability to regenerate limbs.",
                "description_id" to "Salamander unik yang mempertahankan ciri-ciri larvanya sepanjang hidup, dikenal karena kemampuannya menumbuhkan kembali anggota tubuh.",
                "long_description_en" to "The Axolotl is a paedomorphic salamander closely related to the tiger salamander. It is unusual among amphibians in that it reaches adulthood without undergoing metamorphosis. Instead of taking to the land, adults remain aquatic and gilled. The species was originally found in several lakes underlying what is now Mexico City, such as Lake Xochimilco and Lake Chalco.",
                "long_description_id" to "Axolotl adalah salamander paedomorfik yang berkerabat dekat dengan salamander harimau. Hal ini tidak biasa di antara amfibi karena mencapai usia dewasa tanpa mengalami metamorfosis. Alih-alih hidup di darat, axolotl dewasa tetap hidup di air dan bernapas dengan insang. Spesies ini awalnya ditemukan di beberapa danau di bawah yang sekarang menjadi Kota Meksiko, seperti Danau Xochimilco dan Danau Chalco.",
                "fun_fact_en" to "Axolotls can regenerate entire limbs, their heart, and even parts of their brain!",
                "fun_fact_id" to "Axolotl dapat menumbuhkan kembali seluruh anggota tubuh, jantung, dan bahkan bagian otak mereka!",
                "diet_en" to "Carnivore - Worms, insects, small fish",
                "diet_id" to "Karnivora - Cacing, serangga, ikan kecil",
                "lifespan_en" to "10-15 years",
                "lifespan_id" to "10-15 tahun",
                "weight" to "0.06-0.2 kg",
                "length" to "23 cm",
                "special_title_en" to "The Walking Fish",
                "special_title_id" to "Ikan Berjalan",
                "endemic_status_en" to "Endemic to Lake Xochimilco, Mexico",
                "endemic_status_id" to "Endemik Danau Xochimilco, Meksiko",
                "population_trend_en" to "Decreasing",
                "population_trend_id" to "Menurun",
                "activity_period_en" to "Nocturnal",
                "activity_period_id" to "Nokturnal",
                "is_protected" to true,
                "protection_type_en" to "Protected by Law",
                "protection_type_id" to "Dilindungi Undang-Undang",
                "size_category_en" to "Small",
                "size_category_id" to "Kecil",
                "rarity_level_en" to "Critically Rare",
                "rarity_level_id" to "Sangat Langka",
                "population_past" to 6000,
                "population_present" to 700,
                "latitude" to 19.2564,
                "longitude" to -99.1013,
                "country_en" to "Mexico",
                "country_id" to "Meksiko",
                "city_en" to "Xochimilco",
                "city_id" to "Xochimilco",
                "domain" to "Eukarya",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "class" to "Amphibia",
                "order" to "Urodela",
                "family" to "Ambystomatidae",
                "genus" to "Ambystoma",
                "species" to "A. mexicanum",
                "image_url" to null,
                "ar_model_url" to null,
                "audio_url_en" to null,
                "audio_url_id" to null
            ) to "axolotl",

            // 4. Aye-Aye
            hashMapOf(
                "name_en" to "Aye-Aye",
                "name_id" to "Aye-Aye",
                "scientific_name" to "Daubentonia madagascariensis",
                "category_en" to "mammal",
                "category_id" to "mamalia",
                "conservation_status" to "EN",
                "habitat_en" to "Rainforest and deciduous forest",
                "habitat_id" to "Hutan hujan dan hutan gugur",
                "description_en" to "A nocturnal lemur with a long, thin middle finger used to tap on trees and extract insects.",
                "description_id" to "Lemur nokturnal dengan jari tengah yang panjang dan tipis yang digunakan untuk mengetuk pohon dan mengambil serangga.",
                "long_description_en" to "The Aye-aye is a long-fingered lemur, a strepsirrhine primate native to Madagascar with rodent-like teeth that perpetually grow and a special thin middle finger. It is the world's largest nocturnal primate. It taps on trees to find grubs, then gnaws holes in the wood using its forward-slanting incisors to create a small hole in which it inserts its narrow middle finger to pull the grubs out.",
                "long_description_id" to "Aye-aye adalah lemur jari panjang, primata asli Madagaskar dengan gigi seperti hewan pengerat yang terus tumbuh dan jari tengah tipis yang khusus. Ini adalah primata nokturnal terbesar di dunia. Ia mengetuk pohon untuk menemukan larva, kemudian menggerogoti kayu menggunakan gigi serinya untuk membuat lubang kecil, lalu memasukkan jari tengahnya yang sempit untuk menarik larva keluar.",
                "fun_fact_en" to "Locals often believe the Aye-Aye brings bad luck, but it is actually a harmless and helpful insect eater.",
                "fun_fact_id" to "Penduduk setempat sering percaya Aye-Aye membawa nasib buruk, padahal sebenarnya ia adalah pemakan serangga yang tidak berbahaya dan membantu.",
                "diet_en" to "Omnivore - Seeds, fruits, grubs",
                "diet_id" to "Omnivora - Biji-bijian, buah, larva",
                "lifespan_en" to "20-23 years",
                "lifespan_id" to "20-23 tahun",
                "weight" to "2-3 kg",
                "length" to "30-40 cm",
                "special_title_en" to "The Demon Primate",
                "special_title_id" to "Primata Hantu",
                "endemic_status_en" to "Endemic to Madagascar",
                "endemic_status_id" to "Endemik Madagaskar",
                "population_trend_en" to "Decreasing",
                "population_trend_id" to "Menurun",
                "activity_period_en" to "Nocturnal",
                "activity_period_id" to "Nokturnal",
                "is_protected" to true,
                "protection_type_en" to "Protected by Law",
                "protection_type_id" to "Dilindungi Undang-Undang",
                "size_category_en" to "Small",
                "size_category_id" to "Kecil",
                "rarity_level_en" to "Rare",
                "rarity_level_id" to "Langka",
                "population_past" to 10000,
                "population_present" to 1000,
                "latitude" to -18.7669,
                "longitude" to 46.8691,
                "country_en" to "Madagascar",
                "country_id" to "Madagaskar",
                "city_en" to "Antananarivo (Range)",
                "city_id" to "Antananarivo (Sebaran)",
                "domain" to "Eukarya",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "class" to "Mammalia",
                "order" to "Primates",
                "family" to "Daubentoniidae",
                "genus" to "Daubentonia",
                "species" to "D. madagascariensis",
                "image_url" to null,
                "ar_model_url" to null,
                "audio_url_en" to null,
                "audio_url_id" to null
            ) to "aye_aye",

            // 5. Bali Myna (Bali Starling)
            hashMapOf(
                "name_en" to "Bali Myna",
                "name_id" to "Jalak Bali",
                "scientific_name" to "Leucopsar rothschildi",
                "category_en" to "bird",
                "category_id" to "burung",
                "conservation_status" to "CR",
                "habitat_en" to "Dry forests and scrublands",
                "habitat_id" to "Hutan kering dan semak belukar",
                "description_en" to "A stunning white bird with blue eye patches, endemic to the island of Bali.",
                "description_id" to "Burung putih yang memukau dengan area biru di sekitar mata, endemik pulau Bali.",
                "long_description_en" to "The Bali myna, also known as Rothschild's mynah, Bali starling, or Bali mynah, is a medium-sized stocky myna, almost wholly white with a long, drooping crest, and black tips on the wings and tail. The bird has blue bare skin around the eyes, greyish legs and a yellow bill. It is the official animal emblem of Bali.",
                "long_description_id" to "Jalak Bali, juga dikenal sebagai Jalak Rothschild atau Curik Bali, adalah jalak berukuran sedang yang hampir seluruhnya berwarna putih dengan jambul panjang yang menjuntai, serta ujung hitam pada sayap dan ekor. Burung ini memiliki kulit biru telanjang di sekitar mata, kaki keabu-abuan, dan paruh kuning. Ini adalah lambang hewan resmi Bali.",
                "fun_fact_en" to "The Bali Myna is so rare that it was once down to only 6 individuals in the wild!",
                "fun_fact_id" to "Jalak Bali sangat langka hingga pernah hanya tersisa 6 ekor di alam liar!",
                "diet_en" to "Omnivore - Seeds, fruits, insects",
                "diet_id" to "Omnivora - Biji-bijian, buah, serangga",
                "lifespan_en" to "15-20 years",
                "lifespan_id" to "15-20 tahun",
                "weight" to "0.08-0.1 kg",
                "length" to "25 cm",
                "special_title_en" to "Symbol of Bali",
                "special_title_id" to "Lambang Bali",
                "endemic_status_en" to "Endemic to Bali",
                "endemic_status_id" to "Endemik Bali",
                "population_trend_en" to "Increasing",
                "population_trend_id" to "Meningkat",
                "activity_period_en" to "Diurnal",
                "activity_period_id" to "Diurnal",
                "is_protected" to true,
                "protection_type_en" to "Protected by Law",
                "protection_type_id" to "Dilindungi Undang-Undang",
                "size_category_en" to "Small",
                "size_category_id" to "Kecil",
                "rarity_level_en" to "Critically Rare",
                "rarity_level_id" to "Sangat Langka",
                "population_past" to 1000,
                "population_present" to 200,
                "latitude" to -8.1484,
                "longitude" to 114.3677,
                "country_en" to "Indonesia",
                "country_id" to "Indonesia",
                "city_en" to "Bali Barat National Park",
                "city_id" to "Taman Nasional Bali Barat",
                "domain" to "Eukarya",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "class" to "Aves",
                "order" to "Passeriformes",
                "family" to "Sturnidae",
                "genus" to "Leucopsar",
                "species" to "L. rothschildi",
                "image_url" to null,
                "ar_model_url" to null,
                "audio_url_en" to null,
                "audio_url_id" to null
            ) to "bali_myna",

            // 6. Banggai Cardinalfish
            hashMapOf(
                "name_en" to "Banggai Cardinalfish",
                "name_id" to "Capungan Banggai",
                "scientific_name" to "Pterapogon kauderni",
                "category_en" to "fish",
                "category_id" to "ikan",
                "conservation_status" to "EN",
                "habitat_en" to "Coral reefs and seagrass beds",
                "habitat_id" to "Terumbu karang dan padang lamun",
                "description_en" to "A small, strikingly patterned marine fish restricted to the Banggai Islands of Indonesia.",
                "description_id" to "Ikan laut kecil dengan pola mencolok yang terbatas pada Kepulauan Banggai di Indonesia.",
                "long_description_en" to "The Banggai cardinalfish is a small tropical cardinalfish. It is popular in the aquarium trade. Among its distinctive features are the high first dorsal fin, elongated anal and second dorsal fin rays, and deeply forked tail fin. It is one of the few marine fishes that lacks a pelagic larval phase; the male broods the eggs in his mouth.",
                "long_description_id" to "Capungan Banggai adalah ikan kardinal tropis kecil. Ikan ini populer dalam perdagangan akuarium. Di antara fitur khasnya adalah sirip punggung pertama yang tinggi, sirip dubur dan punggung kedua yang memanjang, dan sirip ekor yang bercabang dalam. Ini adalah salah satu dari sedikit ikan laut yang tidak memiliki fase larva pelagis; jantan mengerami telur di dalam mulutnya.",
                "fun_fact_en" to "The father holds the eggs in his mouth until they hatch, not eating for weeks!",
                "fun_fact_id" to "Sang ayah menyimpan telur di mulutnya sampai menetas, dan tidak makan selama berminggu-minggu!",
                "diet_en" to "Carnivore - Plankton, copepods",
                "diet_id" to "Karnivora - Plankton, kopepoda",
                "lifespan_en" to "2-4 years",
                "lifespan_id" to "2-4 tahun",
                "weight" to "0.01 kg",
                "length" to "8 cm",
                "special_title_en" to "Jewel of Banggai",
                "special_title_id" to "Permata Banggai",
                "endemic_status_en" to "Endemic to Banggai Islands",
                "endemic_status_id" to "Endemik Kepulauan Banggai",
                "population_trend_en" to "Decreasing",
                "population_trend_id" to "Menurun",
                "activity_period_en" to "Diurnal",
                "activity_period_id" to "Diurnal",
                "is_protected" to true,
                "protection_type_en" to "Limited Protection",
                "protection_type_id" to "Perlindungan Terbatas",
                "size_category_en" to "Small",
                "size_category_id" to "Kecil",
                "rarity_level_en" to "Rare",
                "rarity_level_id" to "Langka",
                "population_past" to 2000000,
                "population_present" to 1400000,
                "latitude" to -1.6000,
                "longitude" to 123.5000,
                "country_en" to "Indonesia",
                "country_id" to "Indonesia",
                "city_en" to "Central Sulawesi",
                "city_id" to "Sulawesi Tengah",
                "domain" to "Eukarya",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "class" to "Actinopterygii",
                "order" to "Kurtiformes",
                "family" to "Apogonidae",
                "genus" to "Pterapogon",
                "species" to "P. kauderni",
                "image_url" to null,
                "ar_model_url" to null,
                "audio_url_en" to null,
                "audio_url_id" to null
            ) to "banggai_cardinalfish",

            // 7. Bluefin Tuna
            hashMapOf(
                "name_en" to "Bluefin Tuna",
                "name_id" to "Tuna Sirip Biru",
                "scientific_name" to "Thunnus thynnus",
                "category_en" to "fish",
                "category_id" to "ikan",
                "conservation_status" to "EN",
                "habitat_en" to "Open ocean (Pelagic)",
                "habitat_id" to "Laut lepas (Pelagis)",
                "description_en" to "One of the fastest and largest fish in the sea, highly prized for sushi but threatened by overfishing.",
                "description_id" to "Salah satu ikan tercepat dan terbesar di laut, sangat berharga untuk sushi namun terancam oleh penangkapan berlebih.",
                "long_description_en" to "The Atlantic bluefin tuna is a species of tuna in the family Scombridae. It is native to both the western and eastern Atlantic Ocean, as well as the Mediterranean Sea. Atlantic bluefin tuna are capable of reaching speeds of 70 km/h (43 mph). They are warm-blooded, a rare trait among fish, which allows them to hunt in cold waters.",
                "long_description_id" to "Tuna sirip biru Atlantik adalah spesies tuna dalam famili Scombridae. Ikan ini asli dari Samudra Atlantik barat dan timur, serta Laut Mediterania. Tuna sirip biru Atlantik mampu mencapai kecepatan 70 km/jam. Mereka berdarah panas, sifat langka di antara ikan, yang memungkinkan mereka berburu di perairan dingin.",
                "fun_fact_en" to "Bluefin tuna are warm-blooded, allowing them to swim in very cold deep waters!",
                "fun_fact_id" to "Tuna sirip biru berdarah panas, memungkinkan mereka berenang di perairan dalam yang sangat dingin!",
                "diet_en" to "Carnivore - Fish, squid, crustaceans",
                "diet_id" to "Karnivora - Ikan, cumi-cumi, krustasea",
                "lifespan_en" to "15-30 years",
                "lifespan_id" to "15-30 tahun",
                "weight" to "250-680 kg",
                "length" to "2-3 m",
                "special_title_en" to "King of the Ocean",
                "special_title_id" to "Raja Lautan",
                "endemic_status_en" to "Atlantic Ocean & Mediterranean",
                "endemic_status_id" to "Samudra Atlantik & Mediterania",
                "population_trend_en" to "Decreasing",
                "population_trend_id" to "Menurun",
                "activity_period_en" to "Diurnal",
                "activity_period_id" to "Diurnal",
                "is_protected" to true,
                "protection_type_en" to "Quotas Managed",
                "protection_type_id" to "Kuota Diatur",
                "size_category_en" to "Very Large",
                "size_category_id" to "Sangat Besar",
                "rarity_level_en" to "Rare",
                "rarity_level_id" to "Langka",
                "population_past" to 1000000,
                "population_present" to 400000,
                "latitude" to 34.0000,
                "longitude" to -40.0000,
                "country_en" to "International Waters",
                "country_id" to "Perairan Internasional",
                "city_en" to "Atlantic Ocean",
                "city_id" to "Samudra Atlantik",
                "domain" to "Eukarya",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "class" to "Actinopterygii",
                "order" to "Scombriformes",
                "family" to "Scombridae",
                "genus" to "Thunnus",
                "species" to "T. thynnus",
                "image_url" to null,
                "ar_model_url" to null,
                "audio_url_en" to null,
                "audio_url_id" to null
            ) to "bluefin_tuna",

            // 8. California Condor
            hashMapOf(
                "name_en" to "California Condor",
                "name_id" to "Kondor California",
                "scientific_name" to "Gymnogyps californianus",
                "category_en" to "bird",
                "category_id" to "burung",
                "conservation_status" to "CR",
                "habitat_en" to "Rocky shrubland, coniferous forests",
                "habitat_id" to "Semak belukar berbatu, hutan jenis konifera",
                "description_en" to "The largest North American land bird. It became extinct in the wild in 1987 but has since been reintroduced.",
                "description_id" to "Burung darat terbesar di Amerika Utara. Ia punah di alam liar pada tahun 1987 tetapi sejak itu telah diperkenalkan kembali.",
                "long_description_en" to "The California condor is a New World vulture and the largest North American land bird. This condor became extinct in the wild in 1987 when all remaining wild individuals were captured, but has since been reintroduced to northern Arizona and southern Utah, the coastal mountains of central and southern California, and northern Baja California.",
                "long_description_id" to "Kondor California adalah burung pemakan bangkai Dunia Baru dan burung darat terbesar di Amerika Utara. Kondor ini punah di alam liar pada tahun 1987 ketika semua individu liar yang tersisa ditangkap, namun sejak itu telah diperkenalkan kembali ke Arizona utara dan Utah selatan, pegunungan pesisir California tengah dan selatan, serta Baja California utara.",
                "fun_fact_en" to "With a wingspan of 3 meters, they can soar for hours without flapping their wings!",
                "fun_fact_id" to "Dengan rentang sayap 3 meter, mereka bisa terbang melayang selama berjam-jam tanpa mengepakkan sayap!",
                "diet_en" to "Scavenger - Carrion",
                "diet_id" to "Pemakan Bangkai - Bangkai",
                "lifespan_en" to "60 years",
                "lifespan_id" to "60 tahun",
                "weight" to "9-12 kg",
                "length" to "110-140 cm",
                "special_title_en" to "Thunderbird",
                "special_title_id" to "Burung Guntur",
                "endemic_status_en" to "Endemic to SW North America",
                "endemic_status_id" to "Endemik Amerika Utara Barat Daya",
                "population_trend_en" to "Increasing",
                "population_trend_id" to "Meningkat",
                "activity_period_en" to "Diurnal",
                "activity_period_id" to "Diurnal",
                "is_protected" to true,
                "protection_type_en" to "Protected by Law",
                "protection_type_id" to "Dilindungi Undang-Undang",
                "size_category_en" to "Large",
                "size_category_id" to "Besar",
                "rarity_level_en" to "Critically Rare",
                "rarity_level_id" to "Sangat Langka",
                "population_past" to 22,
                "population_present" to 550,
                "latitude" to 36.0544,
                "longitude" to -112.1401,
                "country_en" to "USA",
                "country_id" to "Amerika Serikat",
                "city_en" to "Grand Canyon, Arizona",
                "city_id" to "Grand Canyon, Arizona",
                "domain" to "Eukarya",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "class" to "Aves",
                "order" to "Cathartiformes",
                "family" to "Cathartidae",
                "genus" to "Gymnogyps",
                "species" to "G. californianus",
                "image_url" to null,
                "ar_model_url" to null,
                "audio_url_en" to null,
                "audio_url_id" to null
            ) to "california_condor",

            // 9. Chinese Giant Salamander
            hashMapOf(
                "name_en" to "Chinese Giant Salamander",
                "name_id" to "Salamander Raksasa Tiongkok",
                "scientific_name" to "Andrias davidianus",
                "category_en" to "amphibian",
                "category_id" to "amfibi",
                "conservation_status" to "CR",
                "habitat_en" to "Rocky mountain streams",
                "habitat_id" to "Sungai pegunungan berbatu",
                "description_en" to "The largest living amphibian in the world, often called a 'living fossil'.",
                "description_id" to "Amfibi terbesar yang masih hidup di dunia, sering disebut 'fosil hidup'.",
                "long_description_en" to "The Chinese giant salamander is one of the largest salamanders and one of the largest amphibians in the world. It is fully aquatic and is endemic to rocky mountain streams and lakes in the Yangtze river basin of central China. It is considered critically endangered in the wild due to habitat loss, pollution, and overcollection, as it is considered a delicacy.",
                "long_description_id" to "Salamander raksasa Tiongkok adalah salah satu salamander terbesar dan salah satu amfibi terbesar di dunia. Hewan ini sepenuhnya akuatik dan endemik di sungai dan danau pegunungan berbatu di lembah sungai Yangtze di Tiongkok tengah. Ia dianggap sangat terancam punah di alam liar karena hilangnya habitat, polusi, dan penangkapan berlebihan, karena dianggap sebagai makanan lezat.",
                "fun_fact_en" to "It can make vocalizations that sound like a crying baby!",
                "fun_fact_id" to "Ia bisa mengeluarkan suara yang terdengar seperti bayi menangis!",
                "diet_en" to "Carnivore - Insects, frogs, crabs",
                "diet_id" to "Karnivora - Serangga, katak, kepiting",
                "lifespan_en" to "60 years",
                "lifespan_id" to "60 tahun",
                "weight" to "25-50 kg",
                "length" to "1.1-1.8 m",
                "special_title_en" to "Living Fossil",
                "special_title_id" to "Fosil Hidup",
                "endemic_status_en" to "Endemic to China",
                "endemic_status_id" to "Endemik Tiongkok",
                "population_trend_en" to "Decreasing",
                "population_trend_id" to "Menurun",
                "activity_period_en" to "Nocturnal",
                "activity_period_id" to "Nokturnal",
                "is_protected" to true,
                "protection_type_en" to "Protected by Law",
                "protection_type_id" to "Dilindungi Undang-Undang",
                "size_category_en" to "Large",
                "size_category_id" to "Besar",
                "rarity_level_en" to "Critically Rare",
                "rarity_level_id" to "Sangat Langka",
                "population_past" to 50000,
                "population_present" to 1000,
                "latitude" to 30.5833,
                "longitude" to 114.2667,
                "country_en" to "China",
                "country_id" to "Tiongkok",
                "city_en" to "Yangtze Basin",
                "city_id" to "Lembah Yangtze",
                "domain" to "Eukarya",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "class" to "Amphibia",
                "order" to "Urodela",
                "family" to "Cryptobranchidae",
                "genus" to "Andrias",
                "species" to "A. davidianus",
                "image_url" to null,
                "ar_model_url" to null,
                "audio_url_en" to null,
                "audio_url_id" to null
            ) to "chinese_giant_salamander",

            // 10. Cuban Solenodon
            hashMapOf(
                "name_en" to "Cuban Solenodon",
                "name_id" to "Solenodon Kuba",
                "scientific_name" to "Atopogale cubana",
                "category_en" to "mammal",
                "category_id" to "mamalia",
                "conservation_status" to "EN",
                "habitat_en" to "Dense humid forests",
                "habitat_id" to "Hutan lembab yang lebat",
                "description_en" to "A primitive shrew-like mammal that is one of the few venomous mammals in existence.",
                "description_id" to "Mamalia primitif mirip celurut yang merupakan salah satu dari sedikit mamalia berbisa yang masih ada.",
                "long_description_en" to "The Cuban solenodon is a small, furry, shrew-like mammal endemic to mountainous forests in Cuba. It is nocturnal and burrows underground. It is unique among mammals because it produces toxic saliva, which it uses to subdue prey. It was once thought extinct but was rediscovered in the 1970s.",
                "long_description_id" to "Solenodon Kuba adalah mamalia kecil, berbulu, mirip celurut yang endemik di hutan pegunungan di Kuba. Ia nokturnal dan menggali lubang di bawah tanah. Ia unik di antara mamalia karena menghasilkan air liur beracun, yang digunakannya untuk melumpuhkan mangsa. Ia pernah dianggap punah tetapi ditemukan kembali pada tahun 1970-an.",
                "fun_fact_en" to "It is one of the few venomous mammals, delivering venom through grooves in its teeth!",
                "fun_fact_id" to "Ini adalah salah satu dari sedikit mamalia berbisa, menyalurkan racun melalui alur di giginya!",
                "diet_en" to "Insectivore - Insects, small reptiles",
                "diet_id" to "Insektivora - Serangga, reptil kecil",
                "lifespan_en" to "5-10 years",
                "lifespan_id" to "5-10 tahun",
                "weight" to "1 kg",
                "length" to "40-55 cm",
                "special_title_en" to "Venomous Mammal",
                "special_title_id" to "Mamalia Berbisa",
                "endemic_status_en" to "Endemic to Cuba",
                "endemic_status_id" to "Endemik Kuba",
                "population_trend_en" to "Decreasing",
                "population_trend_id" to "Menurun",
                "activity_period_en" to "Nocturnal",
                "activity_period_id" to "Nokturnal",
                "is_protected" to true,
                "protection_type_en" to "Protected by Law",
                "protection_type_id" to "Dilindungi Undang-Undang",
                "size_category_en" to "Small",
                "size_category_id" to "Kecil",
                "rarity_level_en" to "Rare",
                "rarity_level_id" to "Langka",
                "population_past" to 5000,
                "population_present" to 1000,
                "latitude" to 20.2000,
                "longitude" to -75.0000,
                "country_en" to "Cuba",
                "country_id" to "Kuba",
                "city_en" to "Oriente Province",
                "city_id" to "Provinsi Oriente",
                "domain" to "Eukarya",
                "kingdom" to "Animalia",
                "phylum" to "Chordata",
                "class" to "Mammalia",
                "order" to "Eulipotyphla",
                "family" to "Solenodontidae",
                "genus" to "Atopogale",
                "species" to "A. cubana",
                "image_url" to null,
                "ar_model_url" to null,
                "audio_url_en" to null,
                "audio_url_id" to null
            ) to "cuban_solenodon"
        )

        try {
            var successCount = 0
            sampleAnimals.forEach { (animalData, docId) ->
                animalsCollection.document(docId).set(animalData).await()
                Log.d("FirebaseDataSeeder", "✓ Added: ${animalData["name_en"]}")
                successCount++
            }
            Log.d("FirebaseDataSeeder", "🎉 Successfully added $successCount animals to Firebase!")
        } catch (e: Exception) {
            Log.e("FirebaseDataSeeder", "❌ Error adding animals: ${e.message}", e)
            throw e
        }
    }
}